#Name of workflow
name: Eslint-tcheck

on: push

jobs:
  
  build:
    
    runs-on: Ubuntu-18.04 

    strategy:

      matrix:
        node-version: [14.x]

    steps:

      - uses: action/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: action/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: | 
          make install
        env: 
          CI: true
      - name: Run Linter
        run: |
          make lint    


